language: node_js

sudo: false

install:
- npm ci

cache:
  apt: true
  # keep the npm cache around to speed up installs
  directories:
  - "$HOME/.npm"

node_js:
  - "8"
  - "10"

script:
- npm run lint
- npm run test-cov
